version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/TeamMomentum/bs-url-normalizer"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "java"
enabled = true
