run:
  skip-dirs:

  skip-files:

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - lll
    - testpackage
    - varnamelen
    #DEPRECATED
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

issues:
  exclude-rules:
    - path: ".*_test.go$"
      linters:
        - scopelint
        - exhaustruct

linters-settings:
  depguard:
    rules:
      main:
        list-mode: strict
        allow:
          - $gostd
          - github.com/TeamMomentum/bs-url-normalizer
          - github.com/go-playground/validator/v10
