version: "2"
linters:
  default: all
  disable:
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - godoclint
    - gomodguard # deprecated: replaced by gomodguard_v2
    - gosmopolitan
    - lll
    - noinlineerr
    - testpackage
    - varnamelen
    - wsl # deprecated: replaced by wsl_v5
  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          allow:
            - $gostd
            - github.com/TeamMomentum/bs-url-normalizer
            - github.com/go-playground/validator/v10
            - golang.org/x/net
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - exhaustruct
          - scopelint
        path: .*_test.go$
    paths:
      - third_party$
      - builtin$
      - ^examples/
      - ^js/
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - ^examples/
      - ^js/
