run:
  skip-dirs:

  skip-files:

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - lll

issues:
  exclude-rules:
    - path: ".*_test.go$"
      linters:
        - scopelint
