version: 2
jobs:
  lint_and_test:
    docker:
      - image: dictav/golang-tools:1.10.2

    working_directory: /go/src/github.com/TeamMomentum/bs-url-normalizer

    steps:
      - checkout
      - run: dep ensure
      - run: make lint
      - run: make test

workflows:
  version: 2
  lint_and_test:
    jobs:
    - lint_and_test
