version: 2

wd: &wd /go/src/github.com/TeamMomentum/bs-url-normalizer
defaults: &defaults
  working_directory: *wd
  docker:
    - image: dictav/golang-tools:1.12.9

step_attach: &step_attach
  attach_workspace:
    at: *wd

jobs:
  dep:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-mod-{{ checksum "go.sum" }}
      - run:
          name: vendoring
          command: go mod vendor
          environment:
            GO111MODULE: "on"
      - save_cache:
          key: v1-mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - persist_to_workspace:
          root: *wd
          paths:
            - "*"

  lint:
    <<: *defaults

    steps:
      - *step_attach
      - run: make lint

  test:
    <<: *defaults

    steps:
      - *step_attach
      - run: make test GOOPT="-mod=vendor"

workflows:
  version: 2
  lint_and_test:
    jobs:
      - dep
      - lint:
          requires:
            - dep
      - test:
          requires:
            - dep
