version: 2

goenv: &go_env
  working_directory: &go_wd /go/src/github.com/TeamMomentum/bs-url-normalizer
  chache: &go_cache /go/src/github.com/TeamMomentum/bs-url-normalizer/vendor
  docker:
    - image: dictav/golang-tools:1.17.5
  step_attach: &go_step_attach
    attach_workspace:
      at: *go_wd

jsenv: &js_env
  working_directory: &js_wd ~/bs-url-normalizer/js
  cache: &js_cache ~/bs-url-normalizer/js/node_modules
  docker:
    - image: circleci/node:12
  step_attach: &js_step_attach
    attach_workspace:
      at: *js_wd


jobs:
  # Go
  go_dep:
    <<: *go_env
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-mod-{{ checksum "go.sum" }}
      - run:
          name: vendoring
          command: go mod vendor
          environment:
            GO111MODULE: "on"
      - save_cache:
          key: v1-mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - persist_to_workspace:
          root: *go_wd
          paths:
            - "*"

  go_lint:
    <<: *go_env
    steps:
      - *go_step_attach
      - run: make lint

  go_test:
    <<: *go_env
    steps:
      - *go_step_attach
      - run: make test GOOPT="-mod=vendor"

  # JS
  js_dep:
    <<: *js_env
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-js-{{ checksum "js/package-lock.json" }}

      - run: make -C js node_modules

      - save_cache:
          key: v1-js-{{ checksum "js/package-lock.json" }}
          paths:
            - *js_cache
      - persist_to_workspace:
          root: *js_wd
          paths:
            - "*"

  js_lint:
    <<: *js_env
    steps:
      - *js_step_attach
      - run: make -C js lint

  js_test:
    <<: *js_env
    steps:
      - *js_step_attach
      - run: make -C js test

workflows:
  version: 2
  go:
    jobs:
      - go_dep
      - go_lint:
          requires:
            - go_dep
      - go_test:
          requires:
            - go_dep
  js:
    jobs:
      - js_dep
      - js_lint:
          requires:
            - js_dep
      - js_test:
          requires:
            - js_dep
