name: Go
on:
  pull_request:
    paths-ignore:
      - 'js/**'
      - '**.md'

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57
      - run: make test
