name: Go
on:
  pull_request:
    paths-ignore:
      - 'js/**'
      - '**.md'

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.0'
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
      - run: make test
